Issue/35 Pull request
top-tier-ci-coders/ContinuousIntegrationServer pull request #51
Opened 2019-02-05 11:26 UTC by agylling

Feature, adds the request_push function

Fixes #35

2019-02-05 11:54 UTC, philippaornell approved these changes
Looks good. Maybe you can create an issue that we need more test cases for this method before we merge, so we dont forget it?

2019-02-05 15:13 UTC, agylling commented
Don't know how many more test cases is needed though. There's one branch that is successful (the master), one where the build fails (nobuild) and one where the tests fail (testsfail) so I think all of them are covered?

2019-02-05 21:01 UTC, mstniy requested changes

2019-02-05 21:01 UTC, mstniy commented on src/main/java/CI/GitHandler.java
> +      String path = pull_branch();
pull_branch may fail here (the branch may not exist or a temporary network failure may happen)
One may be inclined to think that the branch should exist at this point because someone pushed to it, but keep in mind the possible race condition that the branch was pushed to and deleted before this callback had the opportunity to run.

2019-02-05 21:01 UTC, mstniy commented on src/test/java/CI/GitHandlerTest.java
> +    gh.request_push();
We need to have assert's here. Maybe we can modify request_push such that it returns a boolean (or even more descriptive, an enum of somthing like PULL_FAILED, BUILD_FAILED, TEST_FAILED, NOTIFICATION_FAILED and so on)

2019-02-05 21:01 UTC, mstniy commented on src/test/java/CI/GitHandlerTest.java
> +  }
We also need to check for a branch that doesn't exist. The current code should crash, I believe (because pull_branch will return a null).

2019-02-06 11:04 UTC, mstniy approved these changes
Seems good

2019-02-06 11:07 UTC, merged